markdown: rdiscount
pygments: true
keep_files: [.git]
author: Dmytro Kovalov
lsi: true
email: dmytro.kovalov@gmail.com
exclude: [bin, spec, Rakefile, Guardfile, _posts/template.md.erb, Gemfile*, template.md.erb, sass, presentations/css/theme/template]
domain: dmytro.github.com
title: 'Dmytro Kovalov: Personal projects, blog, tips and tricks, UNIX development, administration and devops.'
description: |
  Ruby, Perl, Javascript development, UNIX system administration and monitoring. Open source projects developed for my satisfaction and for fun, most of these available on Github or CPAN. Software developed for an employer contains short description, and probably a couple of screen-shots. Please feel free to use, to re-distribute, to critic and to contribute.
changefreq: daily
priority: 1.0


