markdown: rdiscount
pygments: true
keep_files: [.git]
author: Dmytro Kovalov
lsi: true
email: dmytro.kovalov@gmail.com
#
# Design
# --------------------------------------------
assets:
  css_compressor: sass
  js_compressor: uglifier
  cache: true
fonts:
  - Noto+Sans&subset=latin,cyrillic-ext
  - Seymour+One&subset=latin,cyrillic
  - Comfortaa&subset=latin,cyrillic-ext
  - Lobster&subset=latin,cyrillic-ext
  - Inconsolata:700
# --------------------------------------------
exclude: [bin, spec, Rakefile, Guardfile, _posts/template.md.erb, Gemfile*, template.md.erb, sass, presentations/css/theme/template]
domain: dmytro.github.com
title: 'Dmytro Kovalov: Personal projects, blog, tips and tricks, UNIX development, administration and devops.'
description: |
  Ruby, Perl, Javascript development, UNIX system administration and monitoring. Open source projects developed for my satisfaction and for fun, most of these available either on Github or CPAN. For closed source software provided short description, and probably a couple of screen-shots. Please feel free to use, to re-distribute, to critic and to contribute.
changefreq: daily
priority: 1.0

#
# https://github.com/redwallhp/JekyllGalleryTag
# --------------------------------------------
gallerytag:
    dir: images/galleries
    url: /images/galleries
    thumb_width: 120
    thumb_height: 120
    columns: 999
#
# Article series
# Summaries of the articles in series
# --------------------------------------------
series:
  "Request Tracker": 
    text: |
      RT, Request Tracker is a great tool but not the easiest one to use, and certainly not among the prettiest. Some custimizations and development for RT made by me in the course of using and adapring RT for my own taste.

  "Monitoring patterns for Nagios with Nagira API": 
    text: |
      Nagira is RESTful API for Nagios developed by me. Description of some examples of API usage.

  "Github & Jekyll" :
    text: |
      Some information about what this site is made of. Progressing with new tricks as I am learning them.
  
  "Літо на півночі Японії" :
    collapse: true
    text: |
      З десяток років тому ми відкрили для себе "нетипову" Японію - трохи далеку від протоптаних туристичних маршрутів, трохи архаїчну, але тим паче привабливу.<p>
 
      Влітку 2013 року ми мандрували північними частинами острова Хоншю, правда не добираючись до його найпівнічніших частин. В основному - префектурами Акіта, Івате. ПІд час подорожі нас спіткали (чи ми їх) надзвичайна кількість релігійних і історичних святинь, а ще більше - ознак вулканічної активності в цих префектурах. Про це - записи.